# Generated by Django 3.1.5 on 2021-02-15 18:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisionsupport', '0002_noticeboard_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('issues', models.CharField(choices=[('Pest', 'Pest'), ('Disease', 'Disease'), ('Pest and Diseases', 'Pest and Diseases'), ('Others', 'Others')], max_length=50, verbose_name='Issue')),
                ('description', models.TextField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_name', models.CharField(max_length=50, verbose_name='Location Name')),
            ],
            options={
                'verbose_name': 'FarmerIssue',
                'verbose_name_plural': 'FarmerIssues',
            },
        ),
    ]
