# Generated by Django 3.1.5 on 2021-02-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisionsupport', '0003_farmerissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerissue',
            name='reported_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Reported On'),
        ),
    ]
