# Generated by Django 3.1.5 on 2021-02-15 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decisionsupport', '0004_farmerissue_reported_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmerissue',
            options={'verbose_name': 'Farmer Issue', 'verbose_name_plural': 'Farmer Issues'},
        ),
        migrations.AddField(
            model_name='farmerissue',
            name='reported_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
            preserve_default=False,
        ),
    ]
